# Generated by Django 4.1.5 on 2023-01-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planttracker_app', '0002_alter_plant_photo_alter_tag_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
