# Generated by Django 4.1.5 on 2023-01-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planttracker_app', '0005_plant_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='locations',
        ),
    ]
