# Generated by Django 4.1.5 on 2023-01-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planttracker_app', '0006_remove_plant_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='+', to='planttracker_app.location'),
        ),
    ]
