# Generated by Django 4.1.5 on 2023-01-14 21:34

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.TextField()),
                ('family', models.TextField()),
                ('common_name_de', models.TextField()),
                ('common_name_fr', models.TextField()),
                ('common_name_en', models.TextField()),
                ('description_de', models.TextField()),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('tags', models.ManyToManyField(related_name='plants', to='api.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('area', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.plant')),
            ],
        ),
    ]
