# Generated by Django 4.2.1 on 2023-05-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_activationuuid_delete_resetuuid_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantimage',
            name='type',
            field=models.CharField(choices=[('main', 'main'), ('secondary', 'secondary')], default='main', max_length=20),
            preserve_default=False,
        ),
    ]
