# Generated by Django 4.2.1 on 2023-05-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_plantimage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='type',
            field=models.CharField(choices=[('main', 'main'), ('secondary', 'secondary'), ('default', 'default')], max_length=20),
        ),
    ]
