# Generated by Django 4.2.1 on 2023-06-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_plantimage_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
