# Generated by Django 4.2.1 on 2023-06-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_location_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='display_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
