# Generated by Django 4.1.5 on 2023-01-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_plant_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='locations',
        ),
    ]
