# Generated by Django 4.2.1 on 2023-06-03 21:17

import api.models
import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_location_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationimage',
            name='image',
            field=models.ImageField(blank=True, storage=core.storage_backends.PublicMediaStorage(), upload_to=api.models.upload_to, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(blank=True, storage=core.storage_backends.PublicMediaStorage(), upload_to=api.models.upload_to, verbose_name='Photo'),
        ),
    ]
