# Generated by Django 4.1.5 on 2023-03-28 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_plant_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationUUID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
