# Generated by Django 4.2.1 on 2023-06-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_locationimage_image_alter_plantimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='ecology_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='ecology_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='ecology_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='identification_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='identification_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='identification_fr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='common_name_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='common_name_fr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='type',
            field=models.CharField(choices=[('main', 'main'), ('secondary', 'secondary'), ('default', 'default'), ('identification', 'identification')], max_length=20),
        ),
    ]
