# Generated by Django 4.2.1 on 2023-07-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_location_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='temperature',
        ),
    ]
