# Generated by Django 4.2.1 on 2023-05-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_resetuuid_remove_location_image_remove_plant_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationuuid',
            name='expiry_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='resetuuid',
            name='expiry_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
