# Generated by Django 4.2.1 on 2023-05-20 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_activationuuid_expiry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationuuid',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 20, 12, 50, 15136)),
        ),
        migrations.AlterField(
            model_name='resetuuid',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 20, 12, 50, 15438)),
        ),
    ]
