# Generated by Django 4.2.1 on 2023-05-24 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activationuuid_resetuuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationuuid',
            name='email',
        ),
        migrations.RemoveField(
            model_name='resetuuid',
            name='email',
        ),
        migrations.AddField(
            model_name='activationuuid',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resetuuid',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
