# Generated by Django 4.1.5 on 2023-04-16 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_activationuuid_expiry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationuuid',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 10, 33, 45, 475147)),
        ),
        migrations.AlterField(
            model_name='location',
            name='area',
            field=models.PositiveIntegerField(),
        ),
    ]
