# Generated by Django 4.1.5 on 2023-05-07 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_resetuuid_remove_location_image_remove_plant_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationuuid',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 10, 12, 38, 434418)),
        ),
        migrations.AlterField(
            model_name='resetuuid',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 10, 12, 38, 434868)),
        ),
    ]
