# Generated by Django 4.1.5 on 2023-01-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planttracker_app', '0003_alter_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='scientific_name',
            field=models.TextField(unique=True),
        ),
    ]
