# Generated by Django 4.1.5 on 2023-01-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planttracker_app', '0004_alter_plant_scientific_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='locations',
            field=models.ManyToManyField(related_name='plants', to='planttracker_app.location'),
        ),
    ]
