# Generated by Django 4.1.5 on 2023-03-30 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planttracker_app', '0009_activationuuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationuuid',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 18, 20, 38, 684673)),
        ),
    ]
