# Generated by Django 4.1.5 on 2023-03-30 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planttracker_app', '0010_activationuuid_expiry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationuuid',
            name='active',
        ),
        migrations.AlterField(
            model_name='activationuuid',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 18, 25, 22, 769925)),
        ),
    ]
