# Generated by Django 4.1.5 on 2023-04-08 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planttracker_app', '0011_remove_activationuuid_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationuuid',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 15, 56, 49, 539884)),
        ),
    ]
