# Generated by Django 4.1.5 on 2023-04-16 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planttracker_app', '0014_alter_activationuuid_expiry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationuuid',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 10, 13, 17, 711846)),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
