# Generated by Django 4.1.5 on 2023-05-02 15:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import planttracker_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('planttracker_app', '0016_alter_activationuuid_expiry_time_alter_location_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetUUID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('expiry_time', models.DateTimeField(default=datetime.datetime(2023, 5, 3, 15, 35, 27, 568591))),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='image',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='tags',
        ),
        migrations.AlterField(
            model_name='activationuuid',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 15, 35, 27, 568281)),
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=planttracker_app.models.upload_to, verbose_name='Photo')),
                ('alt_en', models.TextField(blank=True)),
                ('alt_fr', models.TextField(blank=True)),
                ('alt_de', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('description_de', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planttracker_app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=planttracker_app.models.upload_to, verbose_name='Photo')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planttracker_app.location')),
            ],
        ),
    ]
